apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-http-server-deployment
  labels:
    app: simple-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: ghcr.io/raelyard/simple-http-server:4277374258
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: simple-http-server-service
      previewService: simple-http-server-service-preview
      autoPromotionEnabled: false
