apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-http-server-deployment
  labels:
    app: simple-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: ghcr.io/raelyard/simple-http-server:4277446468
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 25
      # An AnalysisTemplate is referenced at the second step, which starts an AnalysisRun after
      # the setWeight step. The rollout will not progress to the following step until the
      # AnalysisRun is complete. A failure/error of the analysis will cause the rollout's update to
      # abort, and set the canary weight to zero.
      - analysis:
          templates:
          - templateName: random-fail
          - templateName: always-pass
            clusterScope: true